### PR TITLE
Fix for php 5.4 (Creating is_empty function)

### PR DESCRIPTION
**Pull request by jamesWithPM**
PHP 5.4 does not allow objects in the empty() function.

### CODE REVIEW

**Comment by sambohler** [comment]
Good catch on that bug!  First, please make a GitHub issue so we can track the bug and give you credit.
Then for fixing the bug:
Implementing an `is_empty` helper function adds code complexity that will eventually be technical debt (since `empty` does work fine with method calls in PHP > 5.4).
You also have to track whether the helper function is in every class or loaded properly.  You invoke it in IpnController.php, but it wasn't added as a method to the class.

After doing some further research into the issue, I would suggest we avoid empty altogether in favor of something like:
```php
$country = $address->getCountry();
if (null !== $country && '' !== $country) {
    $buyer->setCountry($country);
}
```
This takes care of the problem without adding too much complexity, and even reduces a redundant function call.  After making the GitHub issue, if you would still like to fix the bug, we would ask you to change your code to use the above method.  Thank you again for your help!

**Comment by jamesWithPM** [comment]
Sure, I can do that real quick. 

But since we're creating a variable now anyway, should we just use the empty function?

```$country = $address->getCountry();
if (!empty($country)) {
    $buyer->setCountry($country);
}```

Or would you prefer the `null` and `''` check?

**Comment by sambohler** [comment]
Originally I wrote the comment to you using the `empty()` function, but `empty()` is just checking for a falsy value and so it could then be made to:

```php
$country = $address->getCountry();
if ($country != false) {
    $buyer->setCountry($country);
}
```

Since `empty()` uses the same bad logic for checking falsy values (something I realized while researching your PR), what we want is a non-null, non-empty string.  The `null` and `''` check would therefore be preferable for better validation logic that won't be as vulnerable to weird bugs (like if we add a field that should accept "0" for instance)

**Comment by jamesWithPM** [comment]
Ok, updated. 
I separated the order/order id checks in `app/code/community/Bitpay/Core/controllers/IpnController.php` in case there is first an issue with pulling the order.

**Comment by sambohler** [comment]
Good job and thank you for your help!

**Pull request merged**
